# Generated by Django 5.2.11 on 2026-02-21 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'wms_category',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='储位编码')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='储位描述')),
            ],
            options={
                'verbose_name': '储位',
                'verbose_name_plural': '储位',
                'db_table': 'wms_storage_location',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供应商名称')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'wms_supplier',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='仓库名称')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='仓库位置')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'wms_warehouse',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作动作')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'wms_audit_log',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='单据编号')),
                ('order_type', models.CharField(choices=[('in', '入库单'), ('out', '出库单')], max_length=10, verbose_name='单据类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '出入库单据',
                'verbose_name_plural': '出入库单据',
                'db_table': 'wms_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品编码')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='计量单位')),
                ('min_stock', models.IntegerField(default=10, verbose_name='预警下限')),
                ('max_stock', models.IntegerField(default=1000, verbose_name='预警上限')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='单价')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms_api.productcategory', verbose_name='商品分类')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms_api.supplier', verbose_name='默认供应商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'wms_product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms_api.order', verbose_name='所属单据')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.product', verbose_name='商品')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.storagelocation', verbose_name='目标/源储位')),
            ],
            options={
                'verbose_name': '单据明细',
                'verbose_name_plural': '单据明细',
                'db_table': 'wms_order_item',
            },
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='wms_api.warehouse', verbose_name='所属仓库'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.product', verbose_name='商品')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.storagelocation', verbose_name='储位')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'wms_inventory',
                'unique_together': {('product', 'storage_location')},
            },
        ),
    ]
